### ISSUE TITLE
EACCES: permission denied, mkdir '/home/node/videos'

### ISSUE THREAD

**Issue by icebob** [blueimp/nightwatch#9]
Hi @blueimp,
thanks this awesome image.
I tried it but I got error.
Command:
```bash
git clone https://github.com/blueimp/nightwatch.git
cd nightwatch
docker-compose run --rm nightwatch
```
Result:
```
Waiting for app:80 to become available ... done
Waiting for chromedriver:4444 to become available ... done
Waiting for chromedriver:6060 to become available ... done

[Failure] Test Suite
========================

There was an error while starting the test runner:

Error: EACCES: permission denied, mkdir '/home/node/videos'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at mkdirp (/home/node/node_modules/nightwatch-video-recorder/index.js:20:8)
    at Object.module.exports.start (/home/node/node_modules/nightwatch-video-recorder/index.js:41:7)
    at Object.module.exports.beforeEach (/home/node/globals.js:5:42)
    at TestSuite.<anonymous> (/usr/lib/node_modules/nightwatch/lib/runner/testsuite.js:459:16)
    at TestSuite.makePromise (/usr/lib/node_modules/nightwatch/lib/runner/testsuite.js:511:8)
    at TestSuite.adaptGlobalHook (/usr/lib/node_modules/nightwatch/lib/runner/testsuite.js:435:15)
    at TestSuite.globalBeforeEach (/usr/lib/node_modules/nightwatch/lib/runner/testsuite.js:427:15)
    at TestSuite.run (/usr/lib/node_modules/nightwatch/lib/runner/testsuite.js:203:10)

```
Do you have any idea, what is the problem? I see that it has no access for videos folder but I don't know why.

Thanks!

**Comment by icebob** [comment]
It's working if I create the `videos` and `screenshots` folders with 777 on host.
